"""autogenerated by genpy from fhwa2_MOOS_to_ROS/FourWheels.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class FourWheels(genpy.Message):
  _md5sum = "2576a2f9111d727e86d328915858ac71"
  _type = "fhwa2_MOOS_to_ROS/FourWheels"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# intented as a helper message
float32 FrontLeft
float32 FrontRight
float32 RearLeft
float32 RearRight
"""
  __slots__ = ['FrontLeft','FrontRight','RearLeft','RearRight']
  _slot_types = ['float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       FrontLeft,FrontRight,RearLeft,RearRight

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FourWheels, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.FrontLeft is None:
        self.FrontLeft = 0.
      if self.FrontRight is None:
        self.FrontRight = 0.
      if self.RearLeft is None:
        self.RearLeft = 0.
      if self.RearRight is None:
        self.RearRight = 0.
    else:
      self.FrontLeft = 0.
      self.FrontRight = 0.
      self.RearLeft = 0.
      self.RearRight = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_4f.pack(_x.FrontLeft, _x.FrontRight, _x.RearLeft, _x.RearRight))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.FrontLeft, _x.FrontRight, _x.RearLeft, _x.RearRight,) = _struct_4f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_4f.pack(_x.FrontLeft, _x.FrontRight, _x.RearLeft, _x.RearRight))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.FrontLeft, _x.FrontRight, _x.RearLeft, _x.RearRight,) = _struct_4f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4f = struct.Struct("<4f")
