# YAML
# Any whitespace in this file will cause errors
#
# Display Parameters ###########################################################
# # Maximum frequency with which messages will be sent past mailroom.cap_freq()
# # Enter 0 for no frequency capping (not recommended - buffer lag errors)
--- 
freq_max: 30
################################################################################
#
# Data input parameters ########################################################
# # g______ Sensors to be processed
sensors: #list
- 'gNovatel'
- 'gPennSt'
- 'gSRI'
- 'gDSRC'
# #
# # z______ Measurments to be processed
desired_variables: #list
- 'zLat'
- 'zLong'
- 'zLatStdDev'
- 'zLongStdDev'
- 'zCourse'
################################################################################
#
# Mark true to display NCAT track meshes and markers
# NCAT: True
#
# Survey Data ##################################################################
# # Where the blender track mesh is zeroed
UTMdatum: # 2 layer nested dictionary
    E: 659300 
    N: 3607850
# # Location of stripe lat/lon survey points
# # -every file in this dir will be processed as a stripe
survey_stripe_loc: '/home/gavlab/rgc0003rosws/fhwa2_MOOS_to_ROS/survey/stripes'
# # Location of lane center lat/lon survey points
# # -every file in this
survey_center_loc: '/home/gavlab/rgc0003rosws/fhwa2_MOOS_to_ROS/survey/centers'
################################################################################