# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fhwa2_gui/src/fhwa2_gui/MatPlot.ui'
#
# Created: Sun Nov 11 21:19:01 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_DataPlotWidget(object):
    def setupUi(self, DataPlotWidget):
        DataPlotWidget.setObjectName("DataPlotWidget")
        DataPlotWidget.resize(936, 215)
        self.gridLayout = QtGui.QGridLayout(DataPlotWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.data_plot = MatDataPlot(DataPlotWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_plot.sizePolicy().hasHeightForWidth())
        self.data_plot.setSizePolicy(sizePolicy)
        self.data_plot.setMinimumSize(QtCore.QSize(50, 50))
        self.data_plot.setBaseSize(QtCore.QSize(0, 0))
        self.data_plot.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.data_plot.setAcceptDrops(True)
        self.data_plot.setAutoFillBackground(False)
        self.data_plot.setObjectName("data_plot")
        self.gridLayout.addWidget(self.data_plot, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(DataPlotWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.topic_edit = QtGui.QLineEdit(self.groupBox)
        self.topic_edit.setObjectName("topic_edit")
        self.verticalLayout.addWidget(self.topic_edit)
        self.comboBox = QtGui.QComboBox(self.groupBox)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.subscribe_topic_button = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subscribe_topic_button.sizePolicy().hasHeightForWidth())
        self.subscribe_topic_button.setSizePolicy(sizePolicy)
        self.subscribe_topic_button.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.subscribe_topic_button.setCheckable(False)
        self.subscribe_topic_button.setObjectName("subscribe_topic_button")
        self.verticalLayout.addWidget(self.subscribe_topic_button)
        self.pause_button = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pause_button.sizePolicy().hasHeightForWidth())
        self.pause_button.setSizePolicy(sizePolicy)
        self.pause_button.setCheckable(True)
        self.pause_button.setObjectName("pause_button")
        self.verticalLayout.addWidget(self.pause_button)
        self.clear_button = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_button.sizePolicy().hasHeightForWidth())
        self.clear_button.setSizePolicy(sizePolicy)
        self.clear_button.setObjectName("clear_button")
        self.verticalLayout.addWidget(self.clear_button)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 1, 1, 1)

        self.retranslateUi(DataPlotWidget)
        QtCore.QMetaObject.connectSlotsByName(DataPlotWidget)

    def retranslateUi(self, DataPlotWidget):
        DataPlotWidget.setWindowTitle(QtGui.QApplication.translate("DataPlotWidget", "Error Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("DataPlotWidget", "Topic", None, QtGui.QApplication.UnicodeUTF8))
        self.topic_edit.setText(QtGui.QApplication.translate("DataPlotWidget", "/", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("DataPlotWidget", "GPS", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("DataPlotWidget", "FHWA2 Combined", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("DataPlotWidget", "SRI", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(3, QtGui.QApplication.translate("DataPlotWidget", "Kapsch", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(4, QtGui.QApplication.translate("DataPlotWidget", "Penn St.", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(5, QtGui.QApplication.translate("DataPlotWidget", "Manual Subscribe", None, QtGui.QApplication.UnicodeUTF8))
        self.subscribe_topic_button.setText(QtGui.QApplication.translate("DataPlotWidget", "Subscribe Topic", None, QtGui.QApplication.UnicodeUTF8))
        self.pause_button.setText(QtGui.QApplication.translate("DataPlotWidget", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.clear_button.setText(QtGui.QApplication.translate("DataPlotWidget", "Remove All", None, QtGui.QApplication.UnicodeUTF8))

from fhwa2_gui.mat_data_plot import MatDataPlot
